#!/usr/bin/env bash

aws configure set aws_access_key_id "$(head -1 /home/k8tls/.aws/credentials)" && \
aws configure set aws_secret_access_key "$(tail -1 /home/k8tls/.aws/credentials)"

./k8s_tlsscan && \
printf "\nJSON Report: \n" && \
cat /tmp/report.json
