#!/usr/bin/env bash

# aws configure set aws_access_key_id "$(head -1 /home/k8tls/.aws/credentials)" && \
# aws configure set aws_secret_access_key "$(tail -1 /home/k8tls/.aws/credentials)"


echo "DEBUG: NAMESPACE=${NAMESPACE}, CHUNK_SIZE=${CHUNK_SIZE}, MAX_PARALLEL_JOBS=${MAX_PARALLEL_JOBS}, CERT_WARN_BEFORE_DAYS=${CERT_WARN_BEFORE_DAYS}"

if [[ "${NAMESPACE}" == "" ]]; then
    NS_ARG="-n -A"
else
    NS_ARG="-n ${NAMESPACE}"
fi

./k8s_tlsscan $NS_ARG -c "${CHUNK_SIZE}" -p "${MAX_PARALLEL_JOBS}" && \
printf "\nJSON Report: \n" && \
cat /tmp/report.json
