name: Docker release Image CI

on:
    push:
        tags:
        - "v[0-9]+.[0-9]+.[0-9]+"
        - "v[0-9]+.[0-9]+.[0-9]+-*"
        - "v*"
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_AUTHTOK }}
        
    - name: Extract Tag Name
      id: extract_tag
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV          
        
    - name: Build and push release
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: kubearmor/k8tls:${{env.RELEASE_TAG }}
    
      
