name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
    - "src/**"
    - "k8s/**"
    - ".github/workflows/ci-docker-release.yml"
  release: 
    types: [published]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_AUTHTOK }}
        
    - name: Build and push latest
      if: ${{ github.ref_name == 'main' }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: kubearmor/k8tls:latest
    
    - name: Build and push version
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: kubearmor/k8tls:${{ github.ref_name}}

      
